### ISSUE TITLE
Map incrustation

### ISSUE THREAD

**Issue by tpoignonec** [bekirbostanci/vda5050_lif_editor#7]
Hi,

Thanks for sharing this project, it's very promising!

Do you intend to incrust the map (png) as an underlay?
It is a central feature for a map editor and, without it, it is very hard to place the nodes.

**Comment by bekirbostanci** [comment]
Hey.
Basically I created add background image feature to layout, but this info can not include to lif. So each time when you open you shall add image manually to layout. 
![image](https://github.com/user-attachments/assets/4f25a7dd-98c4-49f9-a47a-06ecc954385d)
![image](https://github.com/user-attachments/assets/df521b7a-2501-4292-8388-6f7aa9380bb7)

**Comment by tpoignonec** [comment]
Hi, 
That sounds perfect, thanks!
